load("@rules_java//java:defs.bzl", "java_binary", "java_library", "java_test")

package(default_visibility = ["//visibility:private"])

java_library(
    name = "update_lib",
    srcs = glob(
        ["src/main/java/corretto/update/*.java"],
        allow_empty = True,
    ),
    deps = ["@gson//jar"],
)

java_library(
    name = "test_lib",
    srcs = ["src/test/java/corretto/update/Check.java"],
)

java_test(
    name = "json_smoke_test",
    srcs = ["src/test/java/corretto/update/JsonSmokeTest.java"],
    main_class = "corretto.update.JsonSmokeTest",
    use_testrunner = False,
    deps = [
        ":test_lib",
        "@gson//jar",
    ],
)

java_test(
    name = "version_info_test",
    srcs = ["src/test/java/corretto/update/VersionInfoTest.java"],
    main_class = "corretto.update.VersionInfoTest",
    use_testrunner = False,
    deps = [
        ":test_lib",
        ":update_lib",
    ],
)

java_test(
    name = "index_map_test",
    srcs = ["src/test/java/corretto/update/IndexMapTest.java"],
    main_class = "corretto.update.IndexMapTest",
    use_testrunner = False,
    deps = [
        ":test_lib",
        ":update_lib",
    ],
)

java_test(
    name = "derive_test",
    srcs = ["src/test/java/corretto/update/DeriveTest.java"],
    main_class = "corretto.update.DeriveTest",
    use_testrunner = False,
    deps = [
        ":test_lib",
        ":update_lib",
    ],
)

java_test(
    name = "starlark_writer_test",
    srcs = ["src/test/java/corretto/update/StarlarkWriterTest.java"],
    main_class = "corretto.update.StarlarkWriterTest",
    use_testrunner = False,
    deps = [
        ":test_lib",
        ":update_lib",
    ],
)
